version: "3.4"
services:
  backend:
    build: ./api
    platform: linux/x86_64
    # image: ghcr.io/dyzhuu/msabackend:main
    container_name: backend
    ports:
      - 5000:5000
    restart: always

  frontend:
    build: ./web
    platform: linux/x86_64
    # image: ghcr.io/dyzhuu/msafrontend:main
    container_name: frontend
    ports:
      - 80:80
