app = "anime-tracker"

[build]
  dockerfile = "Dockerfile"

[[services]]
    internal_port = 5000
    protocol = "tcp"

    [services.concurrency]
        hard_limit = 25
        soft_limit = 20
        type = "connections"

    [[services.ports]]
        handlers = ["http"]
        port = 5000

    [[services.ports]]
        handlers = ["tls", "http"]
        port = 443

    [[services.tcp_checks]]
        grace_period = "5s"
        interval = "10s"
        restart_limit = 0
        timeout = "2s"


[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[experimental]
    auto_rollback = true
    auto_stop_machines = true